- name: Install python3
  yum:
    name: python3
    state: present
    update_cache: yes

- name: Install python packages
  pip:
    name:
      - flask
      - waitress
    executable: pip3

- name: Copy app files
  copy:
    src: /tmp/app
    dest: /opt/
    owner: ec2-user
    group: ec2-user
